function [ T ] = calculatewOBA( T, C )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
% for ii = 1:size(T,1)
%     wOBAconst = C(C.Season == T.yearID(ii),:);
%     
%     T.wOBA(ii) = double((T.BB(ii) - T.IBB(ii)) * wOBAconst.wBB + ...
%         T.HBP(ii) * wOBAconst.wHBP + ...
%         (T.H(ii) - T.x2B(ii) - T.x3B(ii) - T.HR(ii)) * wOBAconst.w1B + ...
%         T.x2B(ii) * wOBAconst.w2B + ...
%         T.x3B(ii) * wOBAconst.w3B + ...
%         T.HR(ii) * wOBAconst.wHR ) / double(T.AB(ii) + T.BB(ii) - T.IBB(ii) + T.SF(ii) + T.HBP(ii));
% end
% T;
% end

